RUN_STRINGS = (
    "Where do you think you're going?",
    "Huh? what? did they get away?",
    "ZZzzZZzz... Huh? what? oh, just them again, nevermind.",
    "Get back here!",
    "Not so fast...",
    "Look out for the wall!",
    "Don't leave me alone with them!!",
    "You run, you die.",
    "Jokes on you, I'm everywhere",
    "You're gonna regret that...",
    "You could also try /punchme, I hear that's fun.",
    "Go bother someone else, no-one here cares.",
    "You can run, but you can't hide.",
    "Is that all you've got?",
    "I'm behind you...",
    "You've got company!",
    "We can do this the easy way, or the hard way.",
    "You just don't get it, do you?",
    "Yeah, you better run!",
    "Please, remind me how much I care?",
    "I'd run faster if I were you.",
    "That's definitely the droid we're looking for.",
    "May the odds be ever in your favour.",
    "Famous last words.",
    "And they disappeared forever, never to be seen again.",
    "\"Oh, look at me! I'm so cool, I can run from a bot!\" - this person",
    "Yeah yeah, just tap /punchme already.",
    "Here, take this ring and head to Mordor while you're at it.",
    "Legend has it, they're still running...",
    "Unlike Harry Potter, your parents can't protect you from me.",
    "Fear leads to anger. Anger leads to hate. Hate leads to suffering. If you keep running in fear, you might "
    "be the next Vader.",
    "Multiple calculations later, I have decided my interest in your shenanigans is exactly 0.",
    "Legend has it, they're still running.",
    "Keep it up, not sure we want you here anyway.",
    "You're a wiza- Oh. Wait. You're not Harry, keep moving.",
    "NO RUNNING IN THE HALLWAYS!",
    "Hasta la vista, baby.",
    "Who let the dogs out?",
    "It's funny, because no one cares.",
    "Ah, what a waste. I liked that one.",
    "Frankly, my dear, I don't give a damn.",
    "My milkshake brings all the boys to yard... So run faster!",
    "You can't HANDLE the truth!",
    "A long time ago, in a galaxy far far away... Someone would've cared about that. Not anymore though.",
    "Hey, look at them! They're running from the inevitable banhammer... Cute.",
    "Han shot first. So will I.",
    "What are you running after, a white rabbit?",
    "As The Doctor would say... RUN!",
)

SLAP_SAITAMA_TEMPLATES = (
    "Slap gue lagi, bakal gue mute lu.",
    "Jangan slap gue. 😡.",
    [
        "Diyammmmm.",  # normal reply
        "Udah dong woi, gue gabisa mute lu karena lu admin. 🤧.",  # reply to admin
        "tmute"  # command
    ]
)


SLAP_TEMPLATES = (
    "{user2} ditempeleng oleh {user1}.",
    "{user2} berlari kesana kemari karena menghindari {user1}.",
    "{user2} akhirnya tumbang setelah dipukul {user1}.",
    "{user2} sekarang adalah buronan Satpol PP.",
    "{user2} sekarang terkena santet.",
    "{user2} sedang sekarat karena perbuatannya sendiri.",
    "{user2} terkapar lemah akibat kalah melawan {user1}.",
    "{user2} ternyata adalah PKI.",
    "{user2} digeplak keras oleh {user1}.",
    "{user2} terkena azab dari Tuhan.",
    "{user2} telah tercatat sebagai penghuni neraka.",
    "{user2} sebentar lagi akan digelandang kapolda.",
    "{user2} ditolak cintanya oleh {user1}.",
    "{user2} baru saja diblok oleh gebetannya.",
    "{user2} masuk daftar orang paling buruk akhlaknya.",
    "{user2} mencoba menyebrang jalan tol! {user2} tertabrak toyota Innova!.",
    "{user2} menstakling akun mantannya, {user2} pun menangis!.",
    "{user2} dilarikan ke Rumah Sakit akibat kalah bertarung.",
    "{user2} hampir mati karena disantet.",
    "{user2} ditendang hingga tersungkur oleh {user1}.",
    "{user2} memakan buah yang telah diracuni oleh {user1}.",
    "{user2} menjadi gila karena kalah taruhan dengan {user1}.",
    "{user2} mencoba menyerang {user1} namun malah diserang balik.",
    "{user2} dipukul sendal eiger oleh {user1} hingga mukanya tambah jelek.",
    "{user2} sedang bermain bekel menggunakan granat.",
    "{user2} dilumpuhkan oleh {user1}.",
    "{user2} diserang fans KPop.",
    "{user2} dikejar warga karena mencuri pakaian dalam bu RT!",
    "{user2} dismackdown oleh {user1}.",
    "{user2} ditangkap karena kasus korupsi uang monopoli.",
    "{user2} dicoret dari kartu keluarganya.",
    "{user2} meninggal dan bereinkarnasi menjadi ubi jalar.",
    "{user1} memukul {user2} dengan rotan.",
    "{user2} masuk acara 86 karena melanggar lalu lintas.",
    "{user1} menggeplak kepala {user2} dengan sangat keras.",
    "{user1} memegang pipi {user2} dengan lembut, kemudian menendang selangkangannya.",
    "{user1} mengutuk {user2} menjadi batu.",
    "{user1} menyuruh {user2} membangun candi dalam waktu semalam.",
    "{user1} melemparkan {user2} sebuah granat aktif.",
    "{user1} menembak {user2} dengan gas air mata!",
    "{user2} tertangkap basah sedang sedang masturbasi.",
    "{user2} dikirimi dynamit oleh {user1}.",
    "{user1} menabrak {user2} dengan sepeda ontel.",
    "{user2} adalah..........apa hayoo.",
    "{user1} menendang tulang kering {user2}.",
    "{user2} dikalahkan dengan mudah oleh {user1}.",
    "{user1} menempelkan {user2} stiker PKI.",
    "{user2} was a mistake. - '{user1}' ",
    "{user1} menampol {user2} menggunakan sarung tangan thanos.",
    "{user2} diculik alien.",
    "{user1} {hits} {user2} dengan tongkat pramuka!.",
    "{user1} {hits} {user2} memakai papan skate!.",
    "{user1} {hits} {user2} ke tiang gawang!.",    
    "{user1} {hits} {user2} memakai gagang sapu!.",
    "{user1} {hits} {user2} menggunakan mandau terbang!.",
    "{user1} {hits} {user2} dengan sepatu hansip!.",
    "{user1} {hits} {user2} dengan sangat keras!.",
    "{user1} {hits} {user2} dengan batu gunung!.",
    "{user1} {hits} {user2} memakai batok motor supra!.",
    "{user1} {hits} {user2} menggunakan kipas angin!.",
    "{user1} memanggil anggota polisi untuk mengeroyok {user2}.",
    "{user2} berhasil selamat dari serangan macan tutul!.",
    "{user1} {hits} {user2} dengan bongkahan es!.",
    "{user1} {hits} {user2} dengan kencang!.",
    "{user1} {hits} {user2} dengan sekuat tenaga!.",
    "{user1} {hits} {user2} dengan tameng captain amerika.!.",
    "*Anggota TNI memukul {user2}*.",
    "*Anggota Polisi menangkap {user2}*.",
    "*Para napi dipenjara mulai mengeroyok {user2}*.",
    "*Malaikat sekarang memusuhi {user2}*.",
    "*Melihat {user2} sekarat, masyarakat malah senang*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Menghantam {user2} dengan pemadam api*.",
    "{user1} menusuk {user2} dengan bambu runcing!",
    "{user1} ditembak {user2} menggunakan rudal!",        
    "{user1} melempar bom molotov kearah {user2}!",
    "{user1} mengikat {user2} kemudian menggelitikinya!",
    "{user1} menabrak {user2} memakai mobil avanza!",
    "{user1} menarik {user2} kepinggir jurang kemudian mendorongngnya!",
    "{user2} is secretly a Furry!.",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2},Shinaeeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    "( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} dengan sebuah {item}.",
    "{user1} {hits} {user2} tepat di wajahnya menggunakan {item}.",
    "{user1} {hits} {user2} memakai {item}.",
    "{user1} {throws} sebuah {item} ke {user2}.",
    "{user1} mengambil {item} lalu {throws} ke {user2} dengan keras.",
    "{user1} mengirim bom aktif ke rumah {user2}.",
    "{user1} melempar {item} ke {user2} dengan sangat kencang.",
    "{user1} mulai menampar {user2} dengan keras menggunakan {item}.",
    "{user1} menjatuhkan {user2} ke lantai lalu {hits} menggunakan {item}.",
    "{user1} mengambil {item} dan {hits} {user2} dengan itu.",
    "{user1} mengikat {user2} ketembok kemudian {throws} sebuah {item} dengan kencang.",
    "{user1} mendorong dengan keras {user2} ke jurang penyesalan.",
    "{user1} membusur {user2}.",
    "Serigala menggigit kaki {user2}. *nomnomnom*",
    "{user1} {throws} bola bowling ke {user2}, dan tepat mengenai kepalanya.",
    "{user1} memukul {user2} dengan manja...bbbbbb (ง・ω・)ง ====*",
    "{user1} memukul {user2}.",
    "{user1} menendang perut {user2}.",
    "{user1} mensmackdown {user2}.",
    "{user2} dikutuk jadi gerobak siomay!",  
    "{user1} memukul {user2} dengan {item}.",
)

PING_STRING = (
    "PONG!!",
    "Saya disini!",
)

ITEMS = (
    "semvak firaun",
    "batako",
    "TV tabung",
    "helm gojek",
    "helm grab",
    "HP nokia jadul",
    "kipas angin",
    "velg NMax",
    "patung hitler",
    "balok es",
    "batu gunung",
    "stang motor supra",
    "kursi kayu",
    "kasur kapuk",
    "besi",
    "tumpukan buku diary",
    "selang",
    "sepatu laras",
    "sendal swallow",
    "pentungan satpam",
    "sapu lidi",
    "gagang sapu",
    "rotan",
)

THROW = (
    "melemparkan",
    "menjatuhkan",
    "menamparkan",
    "memukulkan",
)

HIT = (
    "memukul",
    "menggeplak",
    "menampar",
    "memukul",
    "menampar",

)

ABUSE_STRINGS = (
    "Fuck off",
    "Stfu go fuck yourself",
    "Ur mum gey",
    "Ur dad lesbo",
    "Bsdk",
    "Nigga",
    "Ur granny tranny",
    "you noob",
    "Relax your Rear,ders nothing to fear,The Rape train is finally here",
    "Stfu bc",
    "Stfu and Gtfo U nub",
    "GTFO bsdk",
    "CUnt",
    " Gay is here",
    "Ur dad gey bc ",
)

EYES = [
    ['⌐■', '■'],
    [' ͠°', ' °'],
    ['⇀', '↼'],
    ['´• ', ' •`'],
    ['´', '`'],
    ['`', '´'],
    ['ó', 'ò'],
    ['ò', 'ó'],
    ['⸌', '⸍'],
    ['>', '<'],
    ['Ƹ̵̡', 'Ʒ'],
    ['ᗒ', 'ᗕ'],
    ['⟃', '⟄'],
    ['⪧', '⪦'],
    ['⪦', '⪧'],
    ['⪩', '⪨'],
    ['⪨', '⪩'],
    ['⪰', '⪯'],
    ['⫑', '⫒'],
    ['⨴', '⨵'],
    ['⩿', '⪀'],
    ['⩾', '⩽'],
    ['⩺', '⩹'],
    ['⩹', '⩺'],
    ['◥▶', '◀◤'],
    ['◍', '◎'],
    ['/͠-', '┐͡-\\'],
    ['⌣', '⌣”'],
    [' ͡⎚', ' ͡⎚'],
    ['≋'],
    ['૦ઁ'],
    ['  ͯ'],
    ['  ͌'],
    ['ළ'],
    ['◉'],
    ['☉'],
    ['・'],
    ['▰'],
    ['ᵔ'],
    [' ﾟ'],
    ['□'],
    ['☼'],
    ['*'],
    ['`'],
    ['⚆'],
    ['⊜'],
    ['>'],
    ['❍'],
    ['￣'],
    ['─'],
    ['✿'],
    ['•'],
    ['T'],
    ['^'],
    ['ⱺ'],
    ['@'],
    ['ȍ'],
    ['  '],
    ['  '],
    ['x'],
    ['-'],
    ['$'],
    ['Ȍ'],
    ['ʘ'],
    ['Ꝋ'],
    [''],
    ['⸟'],
    ['๏'],
    ['ⴲ'],
    ['◕'],
    ['◔'],
    ['✧'],
    ['■'],
    ['♥'],
    [' ͡°'],
    ['¬'],
    [' º '],
    ['⨶'],
    ['⨱'],
    ['⏓'],
    ['⏒'],
    ['⍜'],
    ['⍤'],
    ['ᚖ'],
    ['ᴗ'],
    ['ಠ'],
    ['σ'],
    ['☯']
]

MOUTHS = [
    ['v'],
    ['ᴥ'],
    ['ᗝ'],
    ['Ѡ'],
    ['ᗜ'],
    ['Ꮂ'],
    ['ᨓ'],
    ['ᨎ'],
    ['ヮ'],
    ['╭͜ʖ╮'],
    [' ͟ل͜'],
    [' ͜ʖ'],
    [' ͟ʖ'],
    [' ʖ̯'],
    ['ω'],
    [' ³'],
    [' ε '],
    ['﹏'],
    ['□'],
    ['ل͜'],
    ['‿'],
    ['╭╮'],
    ['‿‿'],
    ['▾'],
    ['‸'],
    ['Д'],
    ['∀'],
    ['!'],
    ['人'],
    ['.'],
    ['ロ'],
    ['_'],
    ['෴'],
    ['ѽ'],
    ['ഌ'],
    ['⏠'],
    ['⏏'],
    ['⍊'],
    ['⍘'],
    ['ツ'],
    ['益'],
    ['╭∩╮'],
    ['Ĺ̯'],
    ['◡'],
    [' ͜つ']
]

EARS = [
    ['q', 'p'],
    ['ʢ', 'ʡ'],
    ['⸮', '?'],
    ['ʕ', 'ʔ'],
    ['ᖗ', 'ᖘ'],
    ['ᕦ', 'ᕥ'],
    ['ᕦ(', ')ᕥ'],
    ['ᕙ(', ')ᕗ'],
    ['ᘳ', 'ᘰ'],
    ['ᕮ', 'ᕭ'],
    ['ᕳ', 'ᕲ'],
    ['(', ')'],
    ['[', ']'],
    ['¯\\_', '_/¯'],
    ['୧', '୨'],
    ['୨', '୧'],
    ['⤜(', ')⤏'],
    ['☞', '☞'],
    ['ᑫ', 'ᑷ'],
    ['ᑴ', 'ᑷ'],
    ['ヽ(', ')ﾉ'],
    ['\\(', ')/'],
    ['乁(', ')ㄏ'],
    ['└[', ']┘'],
    ['(づ', ')づ'],
    ['(ง', ')ง'],
    ['⎝', '⎠'],
    ['ლ(', 'ლ)'],
    ['ᕕ(', ')ᕗ'],
    ['(∩', ')⊃━☆ﾟ.*'],
]

TOSS = (
    "Heads",
    "Tails",
)

DECIDE = (
    "Y.",
    "G.",
    "Iya kali."
)

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "I ran out of tables, will order more.",
    "Go do some work instead of flippin tables."
)
